//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projecto.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCESO
    {
        public int IdAcceso { get; set; }
        public Nullable<System.DateTime> FechaHoraIngreso { get; set; }
        public string Resultado { get; set; }
        public string MotivoDenegacion { get; set; }
        public string Caseta { get; set; }
        public string TipoPersona { get; set; }
        public Nullable<int> IdSocio { get; set; }
        public Nullable<int> IdInvitado { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdVisitante { get; set; }
        public Nullable<int> IdVehiculo { get; set; }
        public Nullable<int> IdUsuarioOficial { get; set; }
    
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual SOCIO SOCIO { get; set; }
        public virtual USUARIO_SISTEMA USUARIO_SISTEMA { get; set; }
        public virtual VEHICULO VEHICULO { get; set; }
        public virtual VISITANTE VISITANTE { get; set; }
    }
}
