//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projecto.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITACORA_SISTEMA
    {
        public int IdBitacora { get; set; }
        public System.DateTime FechaHora { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string TablaAfectada { get; set; }
        public string TipoOperacion { get; set; }
        public string LlaveRegistro { get; set; }
        public string Descripcion { get; set; }
    
        public virtual USUARIO_SISTEMA USUARIO_SISTEMA { get; set; }
    }
}
