//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projecto.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTO_PARTICIPANTE
    {
        public int IdEventoParticipante { get; set; }
        public int IdEvento { get; set; }
        public string TipoParticipante { get; set; }
        public Nullable<int> IdSocio { get; set; }
        public Nullable<int> IdInvitado { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdVisitante { get; set; }
        public string EstadoParticipacion { get; set; }
        public Nullable<bool> Asistencia { get; set; }
    
        public virtual EVENTO EVENTO { get; set; }
    }
}
