//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projecto.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ControlAccesoDBEntities : DbContext
    {
        public ControlAccesoDBEntities()
            : base("name=ControlAccesoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCESO> ACCESO { get; set; }
        public virtual DbSet<BITACORA_SISTEMA> BITACORA_SISTEMA { get; set; }
        public virtual DbSet<EVENTO> EVENTO { get; set; }
        public virtual DbSet<EVENTO_PARTICIPANTE> EVENTO_PARTICIPANTE { get; set; }
        public virtual DbSet<PASE_INVITADO> PASE_INVITADO { get; set; }
        public virtual DbSet<PASE_PROVEEDOR> PASE_PROVEEDOR { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<SOCIO> SOCIO { get; set; }
        public virtual DbSet<USUARIO_SISTEMA> USUARIO_SISTEMA { get; set; }
        public virtual DbSet<VEHICULO> VEHICULO { get; set; }
        public virtual DbSet<VISITANTE> VISITANTE { get; set; }
    }
}
