//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projecto.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASE_PROVEEDOR
    {
        public int IdPaseProveedor { get; set; }
        public string CodigoPase { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<System.DateTime> FechaAutorizada { get; set; }
        public Nullable<System.TimeSpan> HoraInicioAutorizada { get; set; }
        public Nullable<System.TimeSpan> HoraFinAutorizada { get; set; }
        public string EstadoPase { get; set; }
        public Nullable<int> GeneradoPor { get; set; }
    
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual USUARIO_SISTEMA USUARIO_SISTEMA { get; set; }
    }
}
