//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projecto.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASE_INVITADO
    {
        public int IdPaseInvitado { get; set; }
        public string CodigoPase { get; set; }
        public Nullable<int> IdInvitado { get; set; }
        public Nullable<int> IdSocioResponsable { get; set; }
        public Nullable<System.DateTime> FechaGeneracion { get; set; }
        public Nullable<System.DateTime> FechaValidaDesde { get; set; }
        public Nullable<System.DateTime> FechaValidaHasta { get; set; }
        public string EstadoPase { get; set; }
    }
}
