//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projecto.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEHICULO()
        {
            this.ACCESO = new HashSet<ACCESO>();
        }
    
        public int IdVehiculo { get; set; }
        public string Placa { get; set; }
        public string TipoVehiculo { get; set; }
        public string Color { get; set; }
        public Nullable<int> IdSocio { get; set; }
        public Nullable<int> IdProveedor { get; set; }
        public Nullable<int> IdVisitante { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCESO> ACCESO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual SOCIO SOCIO { get; set; }
        public virtual VISITANTE VISITANTE { get; set; }
    }
}
